# Generated by Django 5.0.4 on 2024-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year_of_release',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
