# Generated by Django 5.0.4 on 2024-04-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_actor_gender_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Director', 'Director'), ('Visual Effects (VFX) Artist', 'Visual Effects (VFX) Artist'), ('Sound Engineer', 'Sound Engineer'), ('Editor', 'Editor')], max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
        ),
    ]
